version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: invoices
      POSTGRES_PASSWORD: invoices
      POSTGRES_DB: invoices_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./install.sql:/docker-entrypoint-initdb.d/install.sql
      - ./ddl:/docker-entrypoint-initdb.d/ddl

  msa-invoices:
    build:
      context: ../
    container_name: msa-invoices
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: invoices_db
      DB_USER: invoices
      DB_PASS: invoices
    ports:
      - "8080:8080"
    networks:
      - default

volumes:
  db_data:
