DROP TABLE IF EXISTS T_INVOICES_DETAILS;

CREATE TABLE T_INVOICES_DETAILS (
    IND_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    IND_PRODUCT_NAME CHARACTER VARYING(255) NOT NULL,
    IND_QUANTITY BIGINT NOT NULL,
    IND_UNIT_PRICE NUMERIC(10, 2) NOT NULL,
    IND_SUB_TOTAL NUMERIC(10, 2) NOT NULL,
    IND_INH_ID BIGINT NOT NULL,

    CONSTRAINT PK_T_INVOICES_DETAILS_IND_ID PRIMARY KEY (IND_ID),
    CONSTRAINT FK_T_INVOICES_DETAILS_IND_INH_ID FOREIGN KEY (IND_INH_ID)
        REFERENCES T_INVOICES_HEADERS(INH_ID)
        ON DELETE CASCADE
);